spring:
  application:
    name: chatapp
  datasource:
    url: jdbc:mariadb://localhost:3306/sse_demo?sslMode=DISABLED
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/sse_demo?sslMode=DISABLED
    username: root
    password: password
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
    url: jdbc:mariadb://localhost:3306/sse_demo?sslMode=DISABLED
    user: root
    password: password
    liquibase-schema: sse_demo


logging:
  level:
    io.r2dbc.pool: DEBUG
    dev.miku.r2dbc.mysql: DEBUG
